분실물 게시판 기능 개발 완료
BSSM-BSM/BSM-Frontend-V2 pull request #9
Opened 2023-06-13 15:03 UTC by Ubinquitous

작동은되게만들엇습니다.너무힘들어요

2023-06-13 15:17 UTC, leehj050211 commented
들여쓰기 같은 코드 컨벤션이 기존 프로젝트하고 달라서 변경사항을 추적하기 힘든데 컨벤션만 맞춰주실 수 있나요?
아니면 제가 할까요?

2023-06-13 22:53 UTC, Ubinquitous commented
혹시 prettier 세팅 json코드를 따로 받을 수 있을까요? 제가 다 맞춰놓겠습니다

2023-06-14 02:24 UTC, leehj050211 requested changes
분실물 상세조회하면 에러가 뜨는데 확인하셨나요?
![image](https://github.com/BSSM-BSM/BSM-Frontend-V2/assets/80656849/4c7cb474-088f-4b3b-8549-b5385da8f864)

그리고 밝은 테마로 변경하면 버튼이 잘 안보입니다!
![image](https://github.com/BSSM-BSM/BSM-Frontend-V2/assets/80656849/bd4c15e7-a9b4-4f05-b377-1781bbaf8bf4)

2023-06-14 02:28 UTC, leehj050211 requested changes
라이브러리도 버전이 호환되지 않습니다!
![image](https://github.com/BSSM-BSM/BSM-Frontend-V2/assets/80656849/d8194442-270c-4cc2-bf0a-b86786cb11d4)

2023-06-14 02:41 UTC, Ubinquitous commented
1. 
next app router를 사용할 때 useRouter()를 사용하니 router가 render되기 전에 작업이 수행된다는 오류가 발생해서
useParams로 변경했습니다! 제 로컬호스트에서는 작동하는데 정확한 에러 원인을 잘 모르겠습니다...!!!
<img width="1438" alt="스크린샷 2023-06-14 오전 11 27 15" src="https://github.com/BSSM-BSM/BSM-Frontend-V2/assets/102154880/5a343ec0-42db-44f0-818e-8f982df3e21b">

2.
수정 완료했습니다 확인 부탁드립니다!

3.
스타일드 컴포넌트 호환성을 2.1.3으로 바꿨는데 작동하지가 않습니다.. 따로 해결 방법이 있을까요?

2023-06-14 04:02 UTC, leehj050211 commented
> 스타일드 컴포넌트 호환성을 2.1.3으로 바꿨는데 작동하지가 않습니다.. 따로 해결 방법이 있을까요?

"styled-components": "^5.3.6" 로 하시면 됩니다.

>next app router를 사용할 때 useRouter()를 사용하니 router가 render되기 전에 작업이 수행된다는 오류가 발생해서
useParams로 변경했습니다! 제 로컬호스트에서는 작동하는데 정확한 에러 원인을 잘 모르겠습니다...!!!

```typescript
interface LostFoundDetailProps {
  params: {
    id: number;
  };
}

const LostFoundDetail = ({ params: { id } } : LostFoundDetailProps) => {
```
이렇게 하면 잘 되네요.

2023-06-14 04:04 UTC, leehj050211 requested changes

2023-06-14 04:04 UTC, leehj050211 commented on app/board/lostfound/[id]/page.tsx
> +  });
더미 데이터를 정리해주시면 좋겠습니다!
만약 글이 없다면 이렇게 의미없는 데이터를 넣기보다는 null로 하는 것도 좋을 것 같아요

2023-06-14 06:17 UTC, Ubinquitous commented
수정했습니다 확인부탁드립니다! 아 참고로 생성 로직 확인을 안해봐서 작동안할 수도 있습니다...!!!

2023-06-14 06:26 UTC, leehj050211 approved these changes
👍

2023-06-14 06:28 UTC, merged